# In this scenario:
# - There is a single order of two shipments:
#   - Some parts must be flipped for the order.
#   - Shipments are required to be delivered to specific AGVs.
# - Parts are placed to force arms to hand off parts.
# - Parts must be retrieved from the conveyor.
# - The trial as a whole has a time limit of 500 sec.

time_limit: 500

options:
  insert_models_over_bins: true
  spawn_extra_models: true
  belt_population_cycles: 10
  model_type_aliases:
    order_part1: gasket_part
    order_part2: piston_rod_part
    order_part3: gear_part
    order_part4: pulley_part
    order_part5: disk_part
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    destinations: [agv1, agv2]
    shipment_count: 2
    products:
      part_0:
        type: order_part3
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: order_part4
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [0, 'pi', 0]
      part_2:
        type: order_part3
        pose:
          xyz: [-0.1, 0.2, 0]
          rpy: [0, 0, '3*pi/4']
      part_3:
        type: order_part4
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 'pi/4']

models_over_bins:
  bin1:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 3
        num_models_y: 3
  bin2:
    models:
      disk_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin3:
    models:
      gasket_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin4:
    models:
      piston_rod_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin5:
    models:
      disk_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin6:
    models:
      pulley_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2

belt_models:
  pulley_part:
    28.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/8']
