# In this scenario:
# - There are two orders of one shipment each:
#   - The second will interrupt the first at a convenient time.
#   - The second has no time limit, but should be completed as fast as possible.
#   - After the second order is complete, the first order is to be resumed.
# - A product must be flipped to complete one of the orders.
# - The trial as a whole has a time limit of 500 sec.

time_limit: 500

options:
  insert_models_over_bins: true
  spawn_extra_models: true
  gazebo_state_logging: true
  belt_population_cycles: 5
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part
    order_part3: pulley_part
  visualize_drop_regions: false

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0
    shipment_count: 1
    destinations: [any]
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: order_part1
        pose:
          xyz: [-0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_2:
        type: order_part2
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
  order_1:
    announcement_condition: wanted_products
    announcement_condition_value: 2
    shipment_count: 1
    destinations: [any]
    products:
      part_0:
        type: order_part3
        pose:
          xyz: [0.12, -0.2, 0]
          rpy: ['pi', 0, 0]
      part_1:
        type: order_part3
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: [0, 'pi', 0]
      part_2:
        type: order_part1
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin2:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0]
        xyz_end: [0.5, 0.5, 0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3
  bin3:
    models:
      pulley_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2
  bin4:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3
  bin5:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3


belt_models:
  pulley_part:
    1.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/2']
  disk_part:
    10.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 'pi/2']
