# In this scenario:
# - There is a single order of two shipments:
#   - The order will be updated at an inconvenient time.
#   - The updated order must be delivered to the opposite AGV.
# - The gripper is faulty over the second AGV and will drop a part out of reach.
# - The trial as a whole has a time limit of 500 sec.

time_limit: 500

options:
  insert_models_over_bins: true
  spawn_extra_models: true
  model_type_aliases:
    order_part1: gasket_part
    order_part2: piston_rod_part
    order_part3: gear_part
    order_part4: pulley_part
    order_part5: disk_part
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    destinations: [agv1, agv1]
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [0.0, 0.2, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [0.2, 0.2, 0]
          rpy: [0, 0, 0]
  order_0_update_0:
    announcement_condition: unwanted_products
    announcement_condition_value: 2
    shipment_count: 2
    destinations: [agv2, agv2]
    products:
      part_0:
        type: order_part5
        pose:
          xyz: [-0.1, 0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [0.0, -0.2, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: order_part5
        pose:
          xyz: [0.1, 0.2, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [0.2, -0.2, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin3:
    models:
      gasket_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 3
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 3
  bin2:
    models:
      disk_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 3

sensor_blackout:
  product_count: 2
  duration: 50

drops:
  drop_regions:
    above_agv_2:
      frame: agv2::kit_tray_2
      min:
        xyz: [-0.4, -0.4, 0.0]
      max:
        xyz: [0.4, 0.4, 0.5]
      destination:
        xyz: [1, 1, 0.15]
        rpy: [0, 0, -0.2]
      product_type_to_drop: order_part2
