# In this scenario:
# - There are two orders with two shipments each:
#   - The order will be interrupted at a convenient time.
#   - There are insufficient parts to complete both orders.
#     - The second order is higher priority.
# - Faulty products should not be used to complete orders.
# - Some parts must be retrieved from the conveyor.
# - Parts are placed to force arms to hand off parts.
# - The trial as a whole has a time limit of 500 sec.

time_limit: 500

options:
  insert_models_over_bins: true
  spawn_extra_models: true
  belt_population_cycles: 10
  model_type_aliases:
    order_part1: gasket_part
    order_part2: piston_rod_part
    order_part3: gear_part
    order_part4: pulley_part
    order_part5: disk_part
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    destinations: [any, any]
    shipment_count: 2
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: order_part2
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, '-pi/2']
      part_2:
        type: order_part3
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part4
        pose:
          xyz: [-0.12, 0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: order_part5
        pose:
          xyz: [0, 0, 0]
          rpy: [0, 0, 'pi']
  order_1:
    announcement_condition: wanted_products
    announcement_condition_value: 3
    destinations: [any, any]
    shipment_count: 2
    products:
      part_0:
        type: order_part5
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: order_part3
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, '-pi/2']
      part_2:
        type: order_part2
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part4
        pose:
          xyz: [-0.12, 0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: order_part1
        pose:
          xyz: [0, 0, 0]
          rpy: [0, 0, 'pi/4']

models_over_bins:
  bin1:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin2:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin3:
    models:
      gasket_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin5:
    models:
      disk_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin6:
    models:
      pulley_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2

belt_models:
  gear_part:
    1.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]
  gasket_part:
    15.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]
  piston_rod_part:
    30.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

faulty_products:
  - gasket_part_3
  - piston_rod_part_3
  - gear_part_3
  - pulley_part_3
  - disk_part_3
