# ARIAC 2019 Final 01
# Agility challenges: None
# One order two shipments any AGV.
# Can be completed using a single arm.
# No parts on conveyor.

time_limit: 500

options:
  insert_models_over_bins: true
  spawn_extra_models: true
  belt_population_cycles: 0
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    products:
      part_0:
        type: gasket_part
        pose:
          xyz: [-0.12256111547590082, 0.07714549370867174, 0.0]
          rpy: [0.0, 0.0, -2.09224130008687]
      part_1:
        type: gear_part
        pose:
          xyz: [0.18255783516786045, 0.20118881049733323, 0.0]
          rpy: [0.0, 0.0, 2.019159425978131]
      part_2:
        type: piston_rod_part
        pose:
          xyz: [0.054085110591099536, -0.18132481082248186, 0.0]
          rpy: [0.0, 0.0, 1.4727865540748004]

models_over_bins:
  bin1:
    models:
      gasket_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin2:
    models:
      gear_part:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.3, 0.3, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin3:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  bin6:
    models:
      gasket_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin5:
    models:
      gear_part:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.3, 0.3, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin4:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2

random_seed: 1
