# ARIAC 2019 Final 05
# Agility challenges: Faulty products, Sensor Blackout
# One order two shipments
# Arms required to hand off parts both directions
# Parts must be taken from conveyor

time_limit: 500

options:
  insert_models_over_bins: true
  spawn_extra_models: true
  belt_population_cycles: 10
  gazebo_state_logging: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    destinations: [agv1, agv2]
    products:
      part_0:
        type: gasket_part
        pose:
          xyz: [0.10243821273368592, -0.22577765845289074, 0.0]
          rpy: [0.0, 0.0, -2.9377529918844325]
      part_1:
        type: gear_part
        pose:
          xyz: [0.17690326817886753, -0.02771077734790761, 0.0]
          rpy: [0.0, 0.0, -0.8115567367653718]
      part_2:
        type: piston_rod_part
        pose:
          xyz: [0.09759443245817377, 0.18609293469851598, 0.0]
          rpy: [0.0, 0.0, 1.2560881239229857]
      part_3:
        type: disk_part
        pose:
          xyz: [-0.134850491445285, 0.20842822097406893, 0.0]
          rpy: [0.0, 0.0, 0.7408976128773168]
      part_4:
        type: pulley_part
        pose:
          xyz: [-0.10445124148093288, -0.029072623768140432, 0.0]
          rpy: [0.0, 0.0, 0.3641398796322157]

models_over_bins:
  bin1:
    models:
      gear_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.35, 0.35, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2
  bin2:
    models:
      gasket_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 1.23]
        num_models_x: 1
        num_models_y: 2
  bin3:
    models:
      piston_rod_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.35, 0.35, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2
  bin5:
    models:
      disk_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.35, 0.35, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2
  bin6:
    models:
      gear_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 1.23]
        num_models_x: 1
        num_models_y: 2

belt_models:
  pulley_part:
    30.0:
      pose:
        xyz: [0.0, 0.0, 0.1]
        rpy: [0, 0, 0]

random_seed: 1

faulty_products:
  - gear_part_98
  - gear_part_61

sensor_blackout:
  product_count: 3
  duration: 60
