# In this scenario:
# - There is one order of two shipments.
# - Communication with the sensors will be lost temporarily.
#   - Teams should continue to fill the order as usual during this time.

options:
  insert_models_over_bins: true
  start_box_at_belt_center: false

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    products:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0.1, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: gear_part
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin3:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 5
  bin4:
    models:
      gasket_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.3, 0.47, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin2:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.35, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3

sensor_blackout:
  product_count: 2
  duration: 50

time_limit: -1
