# In this scenario:
# - There are two orders of one shipment each:
#   - The second will interrupt the first at an inconvenient time.
#   - The second has no time limit, but should be completed as fast as possible.
#   - After the second order is complete, the first order is to be resumed.

options:
  insert_models_over_bins: true
  spawn_extra_models: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part
    order_part3: gasket_part
    order_part4: disk_part

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part1
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part2
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: order_part2
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 0]
  order_1:
    announcement_condition: unwanted_products
    announcement_condition_value: 2
    shipment_count: 1
    products:
      part_0:
        type: order_part3
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part3
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part4
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part4
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin1:
    models:
      disk_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.3, 0.47, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
  bin2:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.35, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3
  bin3:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.4, 0.47, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 5
  bin4:
    models:
      gasket_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.3, 0.47, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 3
