# In this scenario:
# - There is one order of two shipments, involving a product that must be flipped.

options:
  insert_models_over_bins: true
  spawn_extra_models: false

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    products:
      part_0:
        type: pulley_part
        pose:
          xyz: [0.1, 0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: pulley_part
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: ['pi', 0, 0]

models_over_bins:
  bin1:
    models:
      pulley_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.15, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2
  bin3:
    models:
      pulley_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.15, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 1
        num_models_y: 2
