# Example perfect shipments for qual_a_3 order_0 and order_1
models_to_spawn:
  agv1::kit_tray_1:
    models:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_1:
        type: order_part1
        pose:
          xyz: [-0.1, -0.15, 0]
          rpy: [0, 0, 'pi/2']
      part_2:
        type: order_part2
        pose:
          xyz: [0.1, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
  agv2::kit_tray_2:
    models:
      part_0:
        type: order_part3
        pose:
          xyz: [0.12, -0.2, 0.1]
          rpy: ['pi', 0, 0]
      part_1:
        type: order_part3
        pose:
          xyz: [-0.12, -0.2, 0.1]
          rpy: [0, 'pi', 0]
      part_2:
        type: order_part1
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]
